apiVersion: v1
kind: Service
metadata:
  name: sre-flask-app
  namespace: sre-demo
  labels:
    app: sre-flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: sre-flask-app
